Bug fix: antlr gen output directory is deleted
[rb/4161](https://rbcommons.com/s/twitter/r/4161/) has both src and dst
under the same common directory to be walked, it also tries to do the
move and delete in the same loop.

Because of some missing checks (fixed in this rb), if the dst directory
is visited first (in alphabetically order) when it is still empty, dst
directory will be deleted first, and later when trying to move files
into this non-existent directory. we would see
```
OSError: [Errno 2] No such file or directory
```

Testing Done:
https://travis-ci.org/peiyuwang/pants/builds/157927376

To repro, change in `test_antlr_gen.py`
```
   PARTS = {'srcroot': 'testprojects/src/antlr',
-           'dir': 'this/is/a/directory',
+           'dir': 'here/is/a/directory',
            'name': 'smoke',
            'prefix': 'SMOKE'}
```
will force destination directory to be visited first, i.e,
destination `BUILD_ROOT/stable/this/is/a/directory` is visited first
before source directory `BUILD_ROOT/stable/testprojects/src/antlr/this/is/a/directory`,
w/o fix would fail and with fix would pass.

Bugs closed: 3838

Reviewed at https://rbcommons.com/s/twitter/r/4205/